config/routes.rb
Rails.application.routes.draw do
  get 'experiments/page1'

  get 'experiments/page2'

  get 'experiments/page3'

  root to: 'pages#batman-vs-superman'
  get 'pages/batman'
  get 'pages/superman'
  post 'pages/batman-vs-superman', action: 'guardar_registro', controller: 'pages', as: 'algo'
  end

app/models/votar.rb
class Votar < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
 	def page1
		render layout: 'bootstrap'
	end
	def page2	
		render layout: 'bootstrap'
	end
	def page3
		render layout: 'bootstrap'
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@heroe = params[:heroe]
		@email = params[:email]
	end
	def guardar_registro
		@heroe = params[:heroe]
		@email = params[:email]
		unless params[:heroe].blank? && params[:email].blank?
			Votar.create(heroe:params[:heroe],email:params[:email])
			redirect_to root_path, 
			notice: "El voto fue guardado"
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/experiments/page1.html.erb
<h1>Experiments#page1</h1>
<h2>1</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum illum quisquam excepturi eius rem distinctio rerum, libero dolores eligendi, hic vel quaerat dolorem, obcaecati totam, ex autem magni maxime similique!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et numquam ab quos eos accusamus soluta adipisci pariatur voluptatem ipsum quo, ad, iure excepturi consectetur impedit facilis debitis porro eum a.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum illum quisquam excepturi eius rem distinctio rerum, libero dolores eligendi, hic vel quaerat dolorem, obcaecati totam, ex autem magni maxime similique!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et numquam ab quos eos accusamus soluta adipisci pariatur voluptatem ipsum quo, ad, iure excepturi consectetur impedit facilis debitis porro eum a.</p>

app/views/experiments/page2.html.erb
<h1>Experiments#page2</h1>
<h2>2</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum illum quisquam excepturi eius rem distinctio rerum, libero dolores eligendi, hic vel quaerat dolorem, obcaecati totam, ex autem magni maxime similique!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et numquam ab quos eos accusamus soluta adipisci pariatur voluptatem ipsum quo, ad, iure excepturi consectetur impedit facilis debitis porro eum a.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum illum quisquam excepturi eius rem distinctio rerum, libero dolores eligendi, hic vel quaerat dolorem, obcaecati totam, ex autem magni maxime similique!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et numquam ab quos eos accusamus soluta adipisci pariatur voluptatem ipsum quo, ad, iure excepturi consectetur impedit facilis debitis porro eum a.</p>

app/views/experiments/page3.html.erb
<h1>Experiments#page3</h1>
<h2>3</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum illum quisquam excepturi eius rem distinctio rerum, libero dolores eligendi, hic vel quaerat dolorem, obcaecati totam, ex autem magni maxime similique!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et numquam ab quos eos accusamus soluta adipisci pariatur voluptatem ipsum quo, ad, iure excepturi consectetur impedit facilis debitis porro eum a.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum illum quisquam excepturi eius rem distinctio rerum, libero dolores eligendi, hic vel quaerat dolorem, obcaecati totam, ex autem magni maxime similique!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et numquam ab quos eos accusamus soluta adipisci pariatur voluptatem ipsum quo, ad, iure excepturi consectetur impedit facilis debitis porro eum a.</p>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superheroes</title>
  <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Bootstrap</title>
	 <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css', media: 'all' %>
</head>
<body>
	<%= render partial: "/layouts/menu"%>
	<%= yield %>
	<%=params[:controller]%>
	<br/>
	<%=params[:action]%>
</body>
</html>

app/views/pages/batman-vs-superman.html.erb
<p class="alert alert-success"><%= flash[:notice] %></p>
<h3>¡Vota por tu héroe favorito!</h3>
<div>
	<a href="/pages/batman.html">
		<img src="./assets/batman.jpg" alt="Go to Batsy's page" class="col-md-6">
	</a>
	<a href="/pages/superman.html">
		<img src="./assets/superman.jpg" alt="Go to Supes' page" class="col-md-6">
	</a>
</div>
<div>
	<form class="col-md-6" action="<%=algo_path %> "method="POST">
	<%= hidden_field_tag :authenticity_token,form_authenticity_token %>
	Superman <br/>
	<input name="heroe" type="hidden" value="Superman"/>
	Email <input name="email"><br/>
	<input type="submit" value="Enviar">
	</form>
</div>
<div>
	<form class="col-md-6" action="<%=algo_path %> "method="POST">
	<%= hidden_field_tag :authenticity_token,form_authenticity_token %>
	Batman <br/>
	<input name="heroe" type="hidden" value="Batman"/>
	Email <input name="email"><br/>
	<input type="submit" value="Enviar">
	</form>
</div>

app/views/pages/batman.html.erb
<h1>I am Batman</h1>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"> </script>

<script type="text/javascript" src="/assets/jquery.backstretch.min.js"></script>

<script type="text/javascript">
  $.backstretch("/assets/batman.jpg")
</script>

app/views/pages/superman.html.erb
<h1>This looks like a job for Superman</h1>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"> </script>

<script type="text/javascript" src="/assets/jquery.backstretch.min.js"></script>

<script type="text/javascript">
  $.backstretch("/assets/superman.jpg")
</script>